### ISSUE TITLE
Looking for examples

### ISSUE THREAD

**Issue by gulatirajat** [bitcoder/cucumber-json-merge#7]
Looking for examples on how such a command can be integrated and executed from nodejs
cucumber-json-merge [options] <report1.json> [report2.json...]

Once way is to use the standard child_process module to use the exec, however it would be good to know if we can hook onto the core cucumber-json-merge module from within the nodejs code

**Comment by bitcoder** [comment]
Hi @gulatirajat , well calling it using exec willl always work for sure.
Meanwhile I will release a new version (0.0.8) that you should be able to use right from the code. Documentation will be updated
